name: Run Org Security Scan

on:
  push:
    branches: [ developer, main ]
  pull_request:
    branches: [ developer, main ]
  workflow_dispatch:

jobs:
  call-org-scan:
    uses: AdamCyberOps/.github/.github/workflows/security-scan.yml@main
    with:
      run_branch: ${{ github.ref_name }}
